<a href="https://colab.research.google.com/github/ashyibo23/pattern-recognition-/blob/main/Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from prettytable import PrettyTable

# load iris dataset
# -----------------------------------------
from sklearn import datasets
iris = datasets.load_iris()

# sample test data
# -----------------------------------------
sample = np.array([
    [6.6, 2.9, 1.3, 2.4],
    [4.7, 3.8, 3.0, 0.2],
    [4.5, 2.1, 4.1, 1.4],
    [5.0, 2.6, 4.5, 1.4],
    [7.0, 3.5, 4.9, 0.6]])


# S_test

# sklearn
# -----------------------------------------
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# split training dataset
X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target, test_size=0.2)

# training and predictions
classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
classifier.fit(X_train, Y_train)

# evaluate
# Y_prediction = classifier.predict(X_test)
# print(confusion_matrix(Y_test, Y_prediction))
# print(classification_report(Y_test, Y_prediction))
# print(accuracy_score(Y_test, Y_prediction))

# sample classification
# -----------------------------------------
Y_prediction = classifier.predict(sample)
# print(Y_prediction)

# prettytable
# -----------------------------------------------------------
pt = PrettyTable(('sample', 'class'))
for row in list(zip(np.round(sample, 5), Y_prediction)): pt.add_row(row)

pt.align['sample'] = 'l'
pt.align['class'] = 'c'

print(pt)

+-------------------+-------+
| sample            | class |
+-------------------+-------+
| [6.6 2.9 1.3 2.4] |   0   |
| [4.7 3.8 3.  0.2] |   0   |
| [4.5 2.1 4.1 1.4] |   1   |
| [5.  2.6 4.5 1.4] |   1   |
| [7.  3.5 4.9 0.6] |   1   |
+-------------------+-------+


In [ ]:
classifier.fit(X_train, Y_train)



KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [ ]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
print(iris.target_names)


['setosa' 'versicolor' 'virginica']


In [ ]:
X = iris.data
y = iris.target
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state= 4)




knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X, y)

y_predict = knn.predict(sample)
print(y_predict)


[0 0 1 1 1]


In [ ]:
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)


In [ ]:
print(Y_train.shape)
print(Y_test.shape)

(120,)
(30,)


In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:

y_predict = knn.predict(sample)
print(y_predict)

[0 0 1 1 1]
